Allow getting the policy of a bucket
paolobarbolini/rusty-s3 pull request #112
Opened 2024-11-21 10:44 UTC by aleb

The struct used to deserialize the response content is very limited, has only the `version` and `id` fields, but it's a good start nevertheless.

Threw in two other small commits, please review each commit separately. Thanks!

2024-11-22 09:40 UTC, aleb commented
Is this of interest?

2024-11-27 08:05 UTC, paolobarbolini requested changes
We are interested in this feature getting merged. Me and @guerinoni work on this project when we have time to.

2024-11-27 08:05 UTC, paolobarbolini commented on src/actions/mod.rs
> +pub use self::get_bucket_policy::{GetBucketPolicy, GetBucketPolicyResponse};
This needs to be gated on the `full` feature as it requires dependencies that are only available when it's enabled. You can check if it compiles afterwards with `cargo check --no-default-features`

2024-11-27 08:05 UTC, paolobarbolini commented on src/actions/mod.rs
> +mod get_bucket_policy;
Same here

2024-11-27 08:05 UTC, paolobarbolini commented on src/actions/get_bucket_policy.rs
> +    pub fn parse_response(s: &str) -> Result<GetBucketPolicyResponse, serde_json::Error> {
Nit: there should be a separator line here

```suggestion
    }

    pub fn parse_response(s: &str) -> Result<GetBucketPolicyResponse, serde_json::Error> {
```

2024-11-29 16:03 UTC, aleb commented
Done

2024-11-29 17:42 UTC, paolobarbolini approved these changes
LGTM. Thank you for the contribution!

2024-11-29 17:42 UTC, merged